//
//  ShowRecipePresenter.swift
//  Milo
//
//  Created by Eldon Chan on 4/2/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowRecipePresentationLogic
{
  func presentRecipe(response: ShowRecipe.GetRecipe.Response)
}

class ShowRecipePresenter: ShowRecipePresentationLogic
{
  weak var viewController: ShowRecipeDisplayLogic?
  
  // MARK: Do something
  
  func presentRecipe(response: ShowRecipe.GetRecipe.Response)
  {
    let recipe = response.recipe
    let displayedRecipe = ShowRecipe.GetRecipe.ViewModel.DisplayedRecipe(image: recipe.image, name: recipe.name, description: recipe.description)
    let viewModel = ShowRecipe.GetRecipe.ViewModel(displayedRecipe: displayedRecipe)
    viewController?.displayRecipe(viewModel: viewModel)
  }
}
