//
//  ShowRecipeModels.swift
//  Milo
//
//  Created by Eldon Chan on 4/2/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowRecipe {
    // MARK: Use cases
    
    enum GetRecipe {
        struct Request {
        }
        struct Response {
            var recipe: Recipe
        }
        struct ViewModel {
            struct DisplayedRecipe {
                var image: UIImage
                var name: String
                var description: String
            }
            var displayedRecipe: DisplayedRecipe
        }
    }
    
    enum AddRecipe {
        struct Request {
        }
    }
}
