//
//  RecipeInteractor.swift
//  Milo
//
//  Created by Eldon Chan on 3/28/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListRecipeBusinessLogic
{
//  func doSomething(request: Recipe.Something.Request)
}

protocol ListRecipeDataStore
{
  //var name: String { get set }
}

class ListRecipeInteractor: ListRecipeBusinessLogic, ListRecipeDataStore
{
  var presenter: ListRecipePresentationLogic?
  var worker: ListRecipeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: Recipe.Something.Request)
//  {
//    worker = RecipeWorker()
//    worker?.doSomeWork()
//
//    let response = Recipe.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
}
