//
//  RecipePresenter.swift
//  Milo
//
//  Created by Eldon Chan on 3/28/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecipePresentationLogic
{
  func presentSomething(response: Recipe.Something.Response)
}

class RecipePresenter: RecipePresentationLogic
{
  weak var viewController: RecipeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Recipe.Something.Response)
  {
    let viewModel = Recipe.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
