//
//  MyRecipePresenter.swift
//  Milo
//
//  Created by Eldon Chan on 4/6/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyRecipePresentationLogic
{
  func presentSomething(response: MyRecipe.Something.Response)
}

class MyRecipePresenter: MyRecipePresentationLogic
{
  weak var viewController: MyRecipeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MyRecipe.Something.Response)
  {
    let viewModel = MyRecipe.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
