//
//  MyRecipePresenter.swift
//  Milo
//
//  Created by Eldon Chan on 4/6/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyRecipePresentationLogic {
  func presentMyRecipes(response: MyRecipe.FetchMyRecipes.Response)
}

class MyRecipePresenter: MyRecipePresentationLogic {
  weak var viewController: MyRecipeDisplayLogic?
  
  // MARK: Do something
  
  func presentMyRecipes(response: MyRecipe.FetchMyRecipes.Response) {

    
    var displayedMyRecipes: [MyRecipe.FetchMyRecipes.ViewModel.DisplayedRecipe] = []
    for recipe in response.myRecipes {
        
        let displayedRecipe = MyRecipe.FetchMyRecipes.ViewModel.DisplayedRecipe(image: recipe.image, name: recipe.name, description: recipe.description)
        displayedMyRecipes.append(displayedRecipe)
    }
    
    let viewModel = MyRecipe.FetchMyRecipes.ViewModel(displayedRecipes: displayedMyRecipes)
    viewController?.displayMyRecipes(viewModel: viewModel)
  }
}
