//
//  ListRecipeModels.swift
//  Milo
//
//  Created by Eldon Chan on 3/28/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListRecipe
{
    // MARK: Use cases
    
    enum FetchRecipes {
        struct Request {
        }
        struct Response {
            var recipes: [Recipe]
        }
        struct ViewModel {
            struct DisplayedRecipes {
                var image: UIImage
                var name: String
                var description: String
            }
            var displayedRecipes: [DisplayedRecipes]
        }
    }
    
    enum AddRecipe {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
