//
//  ListRecipeRouter.swift
//  Milo
//
//  Created by Eldon Chan on 3/28/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListRecipeRoutingLogic {
    func routeToShowRecipe(segue: UIStoryboardSegue?)
}

protocol ListRecipeDataPassing {
    var dataStore: ListRecipeDataStore? { get }
}

class ListRecipeRouter: NSObject, ListRecipeRoutingLogic, ListRecipeDataPassing {
    
    
    weak var viewController: ListRecipeViewController?
    var dataStore: ListRecipeDataStore?
    
    // MARK: Routing
    
    func routeToShowRecipe(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowRecipeViewController
            var destinationDS = destinationVC.router?.dataStore
            passDataToShowRecipe(source: dataStore!, destination: &destinationDS!)
        }
    }
    
    // MARK: Navigation
    
    func navigateToShowRecipe(source: ListRecipeViewController, destination: ShowRecipeViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data.
    
    func passDataToShowRecipe(source: ListRecipeDataStore, destination: inout ShowRecipeDataStore)
    {
        let selectedItemPath = viewController?.collectionView?.indexPathsForSelectedItems
        let selectedItem = selectedItemPath?.first?.item
        destination.recipe = source.recipes?[selectedItem!]
        print("RECIPE ROUTING:",destination.recipe)
        
    }
}
